<?php

/**
 * @file
 * Parse the incoming URL with date_api_ical
 *
 * TODO Figure out how to incorporate VVENUE information into the parser.
 */

/**
 * Implementation of hook_ctools_plugin_api().
 */
function parser_ical_ctools_plugin_api($owner, $api) {
  if ($owner == 'feeds' && $api == 'plugins') {
    return array('version' => 2);
  }
}

/**
 * Implementation of ctools plugin for feeds hook_feeds_plugins().
 */
function parser_ical_feeds_plugins() {
  $path = drupal_get_path('module', 'parser_ical') . '/includes';
  $info = array();
  $info['ParserIcalFeeds'] = array(
    'hidden' => TRUE,
    'handler' => array(
      'parent' => 'FeedsParser',
      'class' => 'ParserIcalFeeds',
      'file' => 'ParserIcal.inc',
      'path' => $path,
    ),
  );
  $info['ParserIcalCreator'] = array(
    'name' => 'iCalCreator parser',
    'description' => 'Use iCalCreator to parse iCal feeds.',
    'help' => 'Parse feeds in the iCal format using the iIcalCreator library.',
    'handler' => array(
      'parent' => 'ParserIcalFeeds',
      'class' => 'ParserIcalCreator',
      'file' => 'ParserIcalCreator.inc',
      'path' => $path,
    ),
  );
  $info['ParserIcalDateModule'] = array(
    'name' => 'Date API iCal parser',
    'description' => 'Use date module api to parse iCal feeds.',
    'help' => 'Parse feeds in the iCal format using api provided by the date module.',
    'handler' => array(
      'parent' => 'ParserIcalFeeds',
      'class' => 'ParserIcalDateModule',
      'file' => 'ParserIcalDate.inc',
      'path' => $path,
    ),
  );
  

  return $info;
}

/**
 * Implementation of hook_help().
 */
function parser_ical_help($path, $arg) {
  switch ($path) {
    case 'admin/modules#description':
      return t('Provide a common iCal parser for Feeds using dateapi.');
  }
}

/**
 * Implementation of hook_enable().
 */
function parser_ical_enable() {
  cache_clear_all('plugins:feeds:plugins', 'cache');
}
